version: "3"

services:
  database:
    image: mongo:4.2.5-bionic
    container_name: "database"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./scripts/initMongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    networks:
      - micro-frontend-network
  container-server:
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        APP_NAME: container
    command: yarn start --scope container dev:server --stream
    container_name: "container-server"
    volumes:
      - "./packages/container:/opt/app/packages/container"
      - "/opt/app/packages/container/node_modules"
      - "./packages/shared:/opt/app/packages/shared"
      - "/opt/app/node_modules"
    ports:
      - "5000:5000"
    networks:
      - micro-frontend-network
  container-client:
    container_name: "container-client"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - APP_NAME=container
    command: yarn start --scope container dev:client --stream
    volumes:
      - "/opt/app/node_modules"
      - "/opt/app/packages/container/node_modules"
      - "./packages/container:/opt/app/packages/container"
      - "./packages/shared:/opt/app/packages/shared"
    ports:
      - "3000:3000"
    networks:
      - micro-frontend-network
  recipe-server:
    container_name: "recipe-server"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - APP_NAME=recipe
    command: yarn start --scope recipe dev:server --stream
    volumes:
      - "/opt/app/node_modules"
      - "/opt/app/packages/recipe/node_modules"
      - "./packages/recipe:/opt/app/packages/recipe"
      - "./packages/shared:/opt/app/packages/shared"
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=database
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "5002:5002"
    depends_on:
      - database
    networks:
      - micro-frontend-network
  recipe-client:
    container_name: "recipe-client"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - APP_NAME=recipe
    command: yarn start --scope recipe dev:client --stream
    volumes:
      - "/opt/app/node_modules"
      - "/opt/app/packages/recipe/node_modules"
      - "./packages/recipe:/opt/app/packages/recipe"
      - "./packages/shared:/opt/app/packages/shared"
    ports:
      - "3002:3002"
    networks:
      - micro-frontend-network
  search-server:
    container_name: "search-server"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - APP_NAME=search
    command: yarn start --scope search dev:server --stream
    volumes:
      - "/opt/app/node_modules"
      - "/opt/app/packages/search/node_modules"
      - "./packages/search:/opt/app/packages/search"
      - "./packages/shared:/opt/app/packages/shared"
    ports:
      - "5001:5001"
    networks:
      - micro-frontend-network
  search-client:
    container_name: "search-client"
    build:
      context: .
      dockerfile: "Dockerfile"
      args:
        - APP_NAME=search
    command: yarn start --scope search dev:client --stream
    volumes:
      - "/opt/app/node_modules"
      - "/opt/app/packages/search/node_modules"
      - "./packages/search:/opt/app/packages/search"
      - "./packages/shared:/opt/app/packages/shared"
    depends_on:
      - search-server
    ports:
      - "3001:3001"
    networks:
      - micro-frontend-network

networks:
  micro-frontend-network:
    driver: bridge

volumes:
  db_data: