# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bootstrap:
    name: Bootstrap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Archive node_modules artifacts
        uses: actions/upload-artifact@v1
        with:
          name: node_modules
          path: node_modules
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [bootstrap]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: node_modules   
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:all
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [bootstrap]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: node_modules  
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint:all
